name: Cache dependencies on main branch
on:
  push:
    branch: main
    if: github.repository_owner == 'annakrystalli'
    paths:
      - '.github/workflows/validate-submission.yaml'
      - '.github/workflows/cache-main.yaml'
  schedule:
    - cron: "10 0 * * *"
      if: github.repository_owner == 'annakrystalli'

jobs:
  cache-on-main:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-r@v2
        with:
          install-r: false
          use-public-rspm: true

      - name: Update R
        run: |
          sudo apt-get update

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: Infectious-Disease-Modeling-Hubs/hubValidations, any::sessioninfo
